### PR TITLE
Allow choosing secret type

### PR DESCRIPTION
**Pull request by kowalczykp**
continuation of PR: https://github.com/bzon/ecr-k8s-secret-creator/pull/2

- bumps go to 1.14 and adds gomod with pinned dependencies
- tested on GKE `Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.9-gke.22", GitCommit:"9bae7fcacb520dfee658b26cc1a9643bf787dfc3", GitTreeState:"clean", BuildDate:"2020-02-27T18:43:37Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}`

### CODE REVIEW

**Comment by kowalczykp** [comment]
@bzon please have a look, this fails on docker push now, due to creds issue i guess? I can restrict pushing only to master. 

There's also one thing to consider -> removing the secret if the type changes, as this is immutable field

**Review by bzon — APPROVED** [review]
LGTM!

**Comment by kowalczykp** [comment]
@bzon just one note -> your docker creds need updating in the repo settings, as this was still not build/deployed to docker registry

**Comment by bzon** [comment]
@kowalczykp I fixed it.

**Pull request merged**
